// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1vH0tBjsNqdvgehjAoK47rCGS1CVenCI',
    appId: '1:148123318410:web:4723466937f62151fc1573',
    messagingSenderId: '148123318410',
    projectId: 'note-taker-app-3c5c3',
    authDomain: 'note-taker-app-3c5c3.firebaseapp.com',
    storageBucket: 'note-taker-app-3c5c3.firebasestorage.app',
    measurementId: 'G-GFXH5VS7R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdePzciyMs59StahAnLk-5Kxjs_q3Ied4',
    appId: '1:148123318410:android:59fe59bf9d379db2fc1573',
    messagingSenderId: '148123318410',
    projectId: 'note-taker-app-3c5c3',
    storageBucket: 'note-taker-app-3c5c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuixcrndU8Zy3yK15IVKm2JNeTtMwyffA',
    appId: '1:148123318410:ios:eb89f1d0440ae30dfc1573',
    messagingSenderId: '148123318410',
    projectId: 'note-taker-app-3c5c3',
    storageBucket: 'note-taker-app-3c5c3.firebasestorage.app',
    iosBundleId: 'com.example.noteTakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuixcrndU8Zy3yK15IVKm2JNeTtMwyffA',
    appId: '1:148123318410:ios:eb89f1d0440ae30dfc1573',
    messagingSenderId: '148123318410',
    projectId: 'note-taker-app-3c5c3',
    storageBucket: 'note-taker-app-3c5c3.firebasestorage.app',
    iosBundleId: 'com.example.noteTakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1vH0tBjsNqdvgehjAoK47rCGS1CVenCI',
    appId: '1:148123318410:web:f54af75a70e6f0bafc1573',
    messagingSenderId: '148123318410',
    projectId: 'note-taker-app-3c5c3',
    authDomain: 'note-taker-app-3c5c3.firebaseapp.com',
    storageBucket: 'note-taker-app-3c5c3.firebasestorage.app',
    measurementId: 'G-4FXTZ63P9B',
  );
}
